repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        args: [--, --allow-branch, main]
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
