site_name: DuckLearn

site_description: "A Python ML toolkit powered by DuckDB"
site_url: ""

repo_url: "https://github.com/Tomosius/ducklearn"
repo_name: "ducklearn"

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    #- navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - navigation.indexes

logo: assets/images/logo.png
favicon: assets/images/favicon.png

extra_css:
  - assets/styles.css

plugins:
  - search
  - autorefs
  - awesome-pages
  - section-index
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_style: google
            show_root_heading: true
            show_root_toc_entry: false
            show_signature_annotations: true
            filters:
              - "!^_"

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets
  - toc:
      permalink: true